name: pylabianca
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py=3.3.0
  - hdf5=1.10.6
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - mkl=2020.4
  - numba=0.53.1
  - numpy=1.21.1
  - numpydoc=1.1.0
  - pandas=1.3.1
  - pip=21.2.3
  - python=3.9.6
  - scikit-learn
  - scipy=1.7.1
  - seaborn=0.11.2
  - setuptools=49.6.0
  - six=1.16.0
  - spyder=5.0.5
  - spyder-kernels=2.0.5
  - tqdm=4.62.0
  - xarray=0.19.0
  - xlrd=2.0.1
  - yaml=0.2.5
  - pip:
    - mne
    - elephant==0.10.0
    - h5io==0.1.7
    - h5netcdf==0.11.0
    - neo==0.10.0
    - patsy==0.5.2
    - pingouin==0.5.1
    - quantities==0.12.5
    - statsmodels==0.13.2
    - -e git+https://github.com/labianca/pylabianca.git#egg=pylabianca
    - -e git+https://github.com/mmagnuski/borsar.git#egg=borsar
    - -e git+https://github.com/mmagnuski/sarna.git#egg=sarna
