name: pylabianca
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py
  - hdf5
  - matplotlib
  - mkl
  - numba
  - numpy
  - numpydoc
  - pandas
  - pip
  - scikit-learn
  - scipy
  - setuptools
  - tqdm
  - xarray
  - xlrd
  - pip:
    - borsar
    - mne
    - elephant
    - h5io
    - h5netcdf
    - neo
    - quantities
    - statsmodels
